server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/authdb

eureka:
  client:
    serviceUrl:
      # This will be overridden by the environment variable in docker-compose
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true # Important in containerized environments

jwt:
  secret: y8J3nD9kL2pQ5xR7vT1wZ6mB4aF8oC0sE3uH9gK7tV2qX5r # MUST be the same as in api-gateway