server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/authdb

user:
  service:
    url: http://user-service:8082