server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to auth-service
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        # Route to user-service
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**

      globalcors: # Add this section for global CORS configuration
        corsConfigurations:
          '[/**]': # Apply CORS to all paths
            allowedOrigins: "http://localhost" # Allow requests from your frontend origin
            allowedMethods: # Allow specific HTTP methods
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS # OPTIONS is crucial for preflight requests
            allowedHeaders: # Allow specific headers
              - Content-Type
              - Authorization # Allow Authorization header for JWT
            allowCredentials: true # Allow cookies/credentials if needed (optional)
            maxAge: 3600 # Cache preflight response for 1 hour (optional)

  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/userdb

jwt:
  secret: your-very-secure-secret-key-needs-to-be-long-and-complex

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"