server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.server: DEBUG
    io.bomtech.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to auth-service using Load Balancer
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # Route to user-service using Load Balancer
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/userdb

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true # API Gateway can also register itself if needed
  instance:
    prefer-ip-address: true # Important in containerized environments

jwt:
  secret: your-very-secure-secret-key-needs-to-be-long-and-complex

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"