server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.server: DEBUG
    io.bomtech.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to auth-service using Load Balancer
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # Route to user-service using Load Balancer
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            # - CustomAuthFilter=USER,ADMIN

        # Route for device-management-service HTTP APIs
        - id: device-management-service-http
          uri: lb://device-management-service # Use Eureka service name
          predicates:
            - Path=/api/devices/** # Match all paths under /api/devices/
          filters:
            # - CustomAuthFilter=USER,ADMIN

        # Route for device-management-service WebSocket (Mobile App)
        - id: device-management-service-ws-mobile
          uri: ws://device-management-service:8083
          predicates:
            - Path=/ws/device/**
          filters:
            # - CustomAuthFilter=USER,ADMIN

        # Route for device-management-service WebSocket (Web Frontend)
        - id: device-management-service-ws-web
          uri: ws://device-management-service:8083
          predicates:
            - Path=/ws/web/updates/**
          filters:
            # - CustomAuthFilter=USER,ADMIN

  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/userdb

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true # API Gateway can also register itself if needed
  instance:
    prefer-ip-address: true # Important in containerized environments

jwt:
  secret: y8J3nD9kL2pQ5xR7vT1wZ6mB4aF8oC0sE3uH9gK7tV2qX5r