server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.server: DEBUG
    io.bomtech.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to auth-service
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        # Route to user-service
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**

  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/userdb

jwt:
  secret: your-very-secure-secret-key-needs-to-be-long-and-complex

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"