server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG

spring:
  cloud:
    gateway:
      routes:
        # Route to auth-service
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        # Route to user-service
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**

      # default-filters:
      #   - AddResponseHeader=X-Response-Time, "#{T(java.time.Instant).now()}"

    # discovery:
    #   locator:
    #     enabled: true
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/userdb

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"