package io.bomtech.device.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

@Data
@NoArgsConstructor
@Document(collection = "devices") // Collection to store device information
public class Device {

    @Id
    private String id; // Unique device ID (could be generated by mobile or server)

    @Indexed
    private String userId; // User associated with this device

    private String deviceName; // e.g., "Phong's iPhone", "Samsung Galaxy S21"
    private String os; // e.g., "iOS", "Android"
    private String appVersion;
    private Instant lastSeen; // Timestamp of the last connection or activity
    private boolean online;

    // --- New fields for backup status ---
    private String lastBackupStatus; // e.g., "INPROGRESS", "COMPLETED", "CANCELED", "FAILED"
    private String lastBackupAccountId; // Zalo Account ID of the last/current backup
    private Instant lastBackupTimestamp; // Timestamp of the last status update for backup
}
